version: "3.5"

services:

  mariadb:
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: task_db
    restart: 

    volumes:
      - ./databases:/var/lib/mysql 

  php:
    build:
      context: php
    restart: always
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html
    depends_on: 
      - mariadb


  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
  depends_on: 
    -mariadb
    -php
