version: "3.5"

services:
  php:
    build:
      context: php
      dockerfile: Dockerfile
    container_name: php74
    depends_on: 
      - mariadb
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:80

  mariadb:
    container_name: mariadb
    image: mariadb:10.4
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: task_db
    volumes:
      - ./databases:/var/lib/mysql 

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb