version: "3.5"

services:


  php:
    build:
      context: php
    ports:
    - 127.0.0.1:8000:80
    volumes:
    - ./app:/var/www/html

  mariadb:
    image: mariadb:10.4
    ports:
    - 127.0.0.1:3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: task_db

    volumes:
    - ./databases:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
    - 127.0.0.1:8080:80
    environment:
      PMA_HOST: mariadb